#!/bin/bash
# #############################################################################
#
# Start the Camomile server
#
# Use like:
#
# camomile [port]
#
# E.g.
#
# camomile
# camomile 8181
#
# #############################################################################

OS="Linux"
case "`uname`" in
Darwin*) OS="OSX";;
Linux*) OS="LINUX";;
esac

cd bin
if [ "$OS" == "OSX" ]
then
  awk -f json.awk -f connections.awk
elif [ "$OS" == LINUX ]
then
  LC_ALL=C gawk -f json.awk -f connections.awk
else
  LC_ALL=C gawk -f json.awk -f connections.awk
fi

JETTY_PORT="-Djetty.port=$1"
if [ "$JETTY_PORT" == "-Djetty.port=" ]
then
  JETTY_PORT=""
fi 

cd ../server 
java ${JETTY_PORT} -jar start.jar lib=../connections OPTIONS=plus
